<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>BracoZS</Authors>
    <Company>BracoZS</Company>
    <Copyright>©BracoZS</Copyright>
    <PackageProjectUrl>https://github.com/BracoZS/ResultPattern</PackageProjectUrl>
    <RepositoryUrl>https://github.com/BracoZS/ResultPattern</RepositoryUrl>
    <PackageTags>result-pattern;csharp;error-handling;functional;success-failure;no-exceptions</PackageTags>
    <Title>ResultPattern.Net</Title>
    <Description>C# implementation of the Result pattern for explicit success/failure handling, avoiding exceptions for predictable cases.</Description>
    <PackageId>$(AssemblyName).Net</PackageId>
    <Product>$(AssemblyName).Net</Product>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <Content Remove="tests\**" />
    <EmbeddedResource Remove="tests\**" />
    <None Remove="tests\**" />
  </ItemGroup>


</Project>
